### ISSUE TITLE
Course discussion page

### ISSUE THREAD

**Issue by umtdg** [studybuddy-cs102/study-buddy#14]
When clicked on a course in the main view, we need to have:
- [x] A way to create and reply to posts (#17),
- [x] An option to leave the course (#17),
- [x] A switch for `wantsToStudy` (#17),
- [ ] A way to like the post,
