### ISSUE TITLE
Registration page enhancements

### ISSUE THREAD

**Issue by umtdg** [studybuddy-cs102/study-buddy#4]
We should accept username, name and surname during registration. It would not be wise to show users' emails on chats/groups/forum.

We also should have a dropdown box kind of thing for gender selection instead of a text field.

Tasks TODO:
- [x] Add mandatory name/surname fields to registration page (#18)
- [x] Better email verification (issue #2)
- [x] Add a mandatory username field to registration page (completed with #7)
- [x] Add gender dropdown (or radio button, or something equivalent) instead of gender text field (completed with #7)
- [x] Make birth year and gender selection mandatory (completed with #7)
- [x] Having a red text under each field to indicate if the field is invalid, empty etc. (completed with #7)

**Comment by hamadaies** [comment]
For the name and surname, we can extract it from the email itself using the name.surname@ug.bilkent.edu.tr. The rest as you listed needs change.

**Comment by umtdg** [comment]
I thought of `name.surname` as `username` because when the user has more than one name, the email only contains one of the names.

**Comment by hamadaies** [comment]
So the username will be from email, but the name and surname manually typed? For multiple last names I guess it can be seen same way as bilkent addresses students with only those two names. Either way will work tho but see whats better implementation

**Comment by umtdg** [comment]
We shouldn't be relying on how Bilkent handles/creates student emails. Students should have the flexibility of passing their full names, only preferred names, or even a completely different name that is different than their original one but they use that name all over the place.

**Comment by hamadaies** [comment]
All tasks are done now
